name: unsheathed_sword
favicon: null
layout_spectrum: 0.4277701380196959
typography_spectrum: 0.6802667607553303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0625972650013864
  lightness: 0.7128482912667096
  saturation: 0.6098331590183079
  rhythmicContrast: 0.4808498041238636
purpose: []
